<?php

/*
 * Le catalogue de reference, tire du document fourni par le client
 * « catalogue_complet_quincaillerie_stock_vente.pdf » : 689 references,
 * 14 rayons, 57 sous-rayons.
 *
 * Chaque entree : [nom, prix indicatif en francs, dessin de repli].
 *
 * Les prix sont des ordres de grandeur credibles pour le marche dakarois, pas
 * des tarifs releves en boutique. Ils sont derives du nom du produit, donc
 * stables d'un semis a l'autre : le meme article vaut toujours la meme chose,
 * ce qui rend une demonstration reproductible. A remplacer par de vrais
 * releves avant toute mise en service.
 *
 * Fichier engendre. Ne pas le modifier a la main.
 */

return [
    'Fer et métallerie' => [
        'icone' => 'beton',
        'sous' => [
            'Barres et profilés' => [
                ['Fer à béton Ø6 mm', 30500, 'rond-strie'],
                ['Fer à béton Ø8 mm', 32000, 'rond-strie'],
                ['Fer à béton Ø10 mm', 24000, 'rond-strie'],
                ['Fer à béton Ø12 mm', 25000, 'rond-strie'],
                ['Fer à béton Ø14 mm', 26000, 'rond-strie'],
                ['Fer à béton Ø16 mm', 27000, 'rond-strie'],
                ['Fer à béton Ø20 mm', 24500, 'rond-strie'],
                ['Fer rond plein', 19500, 'rond-lisse'],
                ['Fer carré plein', 37000, 'defaut'],
                ['Fer plat', 13000, 'fer-plat'],
                ['Fer T', 4600, 'defaut'],
                ['Fer U', 4800, 'defaut'],
                ['Cornière acier', 11000, 'corniere'],
                ['Fer hexagonal', 24500, 'defaut'],
                ['Barre acier', 39000, 'rond-lisse'],
                ['Barre inox', 6900, 'rond-lisse'],
                ['Barre aluminium', 24000, 'rond-lisse'],
                ['Profilé carré', 30000, 'tube-carre'],
                ['Profilé rectangulaire', 36000, 'tube-rect'],
                ['Profilé rond', 40500, 'fil'],
                ['Profilé en U', 37500, 'upn'],
                ['Profilé en T', 37500, 'fil'],
                ['Profilé en L', 33500, 'fil'],
                ['Profilé en H', 32000, 'fil'],
                ['IPN', 19000, 'ipn'],
                ['IPE', 18000, 'ipn'],
                ['HEA', 17000, 'ipn'],
                ['HEB', 17000, 'ipn'],
                ['UPN', 19500, 'upn'],
                ['UPE', 18500, 'upn'],
                ['Rail métallique', 16000, 'defaut'],
                ['Profilé plafond', 39500, 'fil'],
                ['Profilé cloison', 10000, 'fil'],
                ['Profilé portail', 8700, 'fil'],
            ],
            'Tubes' => [
                ['Tube carré noir', 12500, 'tube-carre'],
                ['Tube carré galvanisé', 14000, 'tube-carre'],
                ['Tube rectangulaire noir', 16000, 'tube-rect'],
                ['Tube rectangulaire galvanisé', 22000, 'tube-rect'],
                ['Tube rond noir', 12000, 'tube-rond'],
                ['Tube rond galvanisé', 23500, 'tube-rond'],
                ['Tube acier soudé', 15000, 'tube-rond'],
                ['Tube acier sans soudure', 7200, 'tube-rond'],
                ['Tube inox', 22000, 'tube-rond'],
                ['Tube aluminium', 23000, 'tube-rond'],
                ['Tube cuivre', 18500, 'tube-rond'],
            ],
            'Tôles' => [
                ['Tôle noire', 23500, 'tole-plane'],
                ['Tôle galvanisée', 6600, 'tole-plane'],
                ['Tôle inox', 16500, 'tole-plane'],
                ['Tôle aluminium', 31500, 'tole-plane'],
                ['Tôle larmée', 26500, 'tole-larmee'],
                ['Tôle perforée', 26500, 'tole-plane'],
                ['Tôle déployée', 6000, 'tole-plane'],
                ['Tôle ondulée', 25500, 'tole-ondulee'],
                ['Tôle nervurée', 33500, 'tole-bac'],
                ['Tôle bac acier', 13500, 'tole-bac'],
                ['Tôle prélaquée', 13500, 'tole-plane'],
                ['Tôle plane', 19500, 'tole-plane'],
                ['Tôle électrozinguée', 8100, 'tole-plane'],
            ],
            'Grillage, fils et câbles' => [
                ['Fil de fer', 6300, 'fil'],
                ['Fil galvanisé', 3900, 'fil'],
                ['Fil recuit', 7300, 'fil'],
                ['Fil d\'attache', 20000, 'fil'],
                ['Fil inox', 10000, 'fil'],
                ['Fil d\'acier', 26000, 'fil'],
                ['Grillage soudé', 25000, 'grillage'],
                ['Grillage galvanisé', 19000, 'grillage'],
                ['Grillage simple torsion', 26000, 'grillage'],
                ['Treillis soudé', 6100, 'treillis'],
                ['Chaîne acier', 21500, 'chaine'],
                ['Câble acier', 18000, 'fil'],
                ['Câble galvanisé', 27000, 'fil'],
                ['Élingue', 15000, 'defaut'],
                ['Manille', 8400, 'defaut'],
                ['Crochet', 10000, 'defaut'],
                ['Anneau', 7600, 'defaut'],
                ['Mousqueton', 24500, 'defaut'],
            ],
        ],
    ],
    'Quincaillerie' => [
        'icone' => 'quincaillerie',
        'sous' => [
            'Visserie' => [
                ['Vis à bois', 4200, 'vis'],
                ['Vis à métal', 10500, 'vis'],
                ['Vis autoforeuse', 2500, 'vis'],
                ['Vis autoperceuse', 9600, 'vis'],
                ['Vis à tôle', 2100, 'tole-plane'],
                ['Vis placo', 8500, 'vis'],
                ['Vis terrasse', 9600, 'vis'],
                ['Vis inox', 1600, 'vis'],
                ['Vis tête fraisée', 1800, 'vis'],
                ['Vis tête hexagonale', 2500, 'vis'],
                ['Vis tête ronde', 11500, 'vis'],
                ['Vis six pans', 11000, 'vis'],
                ['Vis métrique', 9400, 'vis'],
                ['Vis machine', 3300, 'vis'],
                ['Vis à béton', 3300, 'vis'],
                ['Vis charpente', 3200, 'vis'],
                ['Tirefond', 5100, 'vis'],
            ],
            'Boulonnerie' => [
                ['Boulon hexagonal', 13000, 'boulon'],
                ['Boulon inox', 12500, 'boulon'],
                ['Boulon galvanisé', 9800, 'boulon'],
                ['Boulon carrosserie', 6100, 'boulon'],
                ['Boulon haute résistance', 9100, 'boulon'],
                ['Écrou hexagonal', 5600, 'boulon'],
                ['Écrou frein', 12000, 'boulon'],
                ['Écrou papillon', 2700, 'boulon'],
                ['Écrou borgne', 10500, 'boulon'],
                ['Écrou carré', 3900, 'boulon'],
                ['Écrou à embase', 10500, 'boulon'],
                ['Rondelle plate', 4000, 'boulon'],
                ['Rondelle grower', 2100, 'boulon'],
                ['Rondelle éventail', 3400, 'boulon'],
                ['Rondelle frein', 3900, 'boulon'],
                ['Rondelle large', 11500, 'boulon'],
                ['Goujon', 2500, 'boulon'],
                ['Tige filetée', 7200, 'boulon'],
            ],
            'Fixations' => [
                ['Cheville nylon', 2400, 'cheville'],
                ['Cheville métallique', 3300, 'cheville'],
                ['Cheville à expansion', 2300, 'cheville'],
                ['Cheville Molly', 6000, 'cheville'],
                ['Cheville béton', 8100, 'cheville'],
                ['Cheville placo', 3400, 'cheville'],
                ['Cheville chimique', 2700, 'cheville'],
                ['Scellement chimique', 5300, 'defaut'],
                ['Rivet', 6900, 'defaut'],
                ['Rivet pop', 4000, 'defaut'],
                ['Agrafe', 1500, 'clou'],
                ['Collier de serrage', 7400, 'defaut'],
                ['Collier métallique', 5400, 'defaut'],
                ['Collier plastique', 1400, 'defaut'],
                ['Serre-câble', 3200, 'fil'],
                ['Attache métallique', 9000, 'defaut'],
            ],
            'Serrurerie' => [
                ['Serrure à encastrer', 37500, 'cadenas'],
                ['Serrure en applique', 38000, 'cadenas'],
                ['Serrure de portail', 43500, 'cadenas'],
                ['Serrure de garage', 35000, 'cadenas'],
                ['Serrure électrique', 37000, 'cadenas'],
                ['Cylindre', 18000, 'cadenas'],
                ['Barillet', 19500, 'defaut'],
                ['Cadenas', 26500, 'cadenas'],
                ['Verrou', 5700, 'cadenas'],
                ['Targette', 19500, 'cadenas'],
                ['Loquet', 4300, 'defaut'],
                ['Pêne', 8400, 'defaut'],
                ['Gâche', 25500, 'defaut'],
                ['Poignée de porte', 15000, 'defaut'],
                ['Bouton de porte', 18000, 'defaut'],
                ['Plaque de serrure', 24500, 'cadenas'],
                ['Rosace', 40000, 'defaut'],
                ['Ferme-porte', 44500, 'defaut'],
                ['Barre anti-panique', 11000, 'rond-lisse'],
            ],
            'Charnières et accessoires' => [
                ['Charnière simple', 4400, 'charniere'],
                ['Charnière renforcée', 10500, 'charniere'],
                ['Charnière piano', 4700, 'charniere'],
                ['Charnière de portail', 3600, 'charniere'],
                ['Charnière à ressort', 5500, 'charniere'],
                ['Paumelle', 8300, 'charniere'],
                ['Pivot', 6200, 'defaut'],
                ['Gond', 11000, 'charniere'],
                ['Butée de porte', 8000, 'defaut'],
                ['Arrêt de porte', 10500, 'defaut'],
                ['Roulette fixe', 6600, 'defaut'],
                ['Roulette pivotante', 10500, 'defaut'],
                ['Galet', 2700, 'poulie'],
                ['Support métallique', 1800, 'defaut'],
                ['Équerre de fixation', 5700, 'defaut'],
            ],
        ],
    ],
    'Outillage à main' => [
        'icone' => 'outillage',
        'sous' => [
            'Frappe' => [
                ['Marteau de mécanicien', 11000, 'marteau'],
                ['Marteau de charpentier', 13500, 'marteau'],
                ['Marteau de menuisier', 8700, 'marteau'],
                ['Marteau arrache-clou', 3800, 'clou'],
                ['Marteau rivoir', 8000, 'marteau'],
                ['Marteau boule', 5200, 'marteau'],
                ['Massette', 11000, 'marteau'],
                ['Maillet caoutchouc', 8100, 'marteau'],
            ],
            'Tournevis et embouts' => [
                ['Tournevis plat', 7200, 'vis'],
                ['Tournevis cruciforme', 7800, 'vis'],
                ['Tournevis Pozidriv', 4300, 'vis'],
                ['Tournevis Torx', 7400, 'vis'],
                ['Tournevis isolé', 6800, 'vis'],
                ['Tournevis précision', 4500, 'vis'],
                ['Porte-embout', 5700, 'defaut'],
                ['Jeu de tournevis', 1600, 'vis'],
                ['Embout plat', 5200, 'defaut'],
                ['Embout cruciforme', 5200, 'defaut'],
                ['Embout Torx', 5900, 'defaut'],
                ['Embout six pans', 1600, 'defaut'],
            ],
            'Clés' => [
                ['Clé plate', 3900, 'defaut'],
                ['Clé mixte', 8600, 'defaut'],
                ['Clé à pipe', 14000, 'ipn'],
                ['Clé à œil', 34000, 'defaut'],
                ['Clé à molette', 19000, 'defaut'],
                ['Clé à griffe', 27500, 'defaut'],
                ['Clé à chaîne', 3500, 'chaine'],
                ['Clé Allen', 32000, 'defaut'],
                ['Clé Torx', 6800, 'defaut'],
                ['Clé à bougie', 31000, 'defaut'],
                ['Clé dynamométrique', 6700, 'defaut'],
                ['Jeu de clés', 29500, 'defaut'],
                ['Coffret de douilles', 28500, 'defaut'],
                ['Douille 6 pans', 33000, 'defaut'],
                ['Douille 12 pans', 31500, 'defaut'],
                ['Rallonge de douille', 14000, 'defaut'],
                ['Cardan', 11000, 'defaut'],
            ],
            'Pinces' => [
                ['Pince universelle', 9600, 'defaut'],
                ['Pince coupante', 11500, 'defaut'],
                ['Pince à bec long', 8800, 'defaut'],
                ['Pince à bec rond', 10000, 'rond-lisse'],
                ['Pince multiprise', 13500, 'defaut'],
                ['Pince étau', 15500, 'defaut'],
                ['Pince à circlips', 12500, 'defaut'],
                ['Pince à dénuder', 6800, 'defaut'],
                ['Pince à sertir', 14000, 'defaut'],
                ['Pince à riveter', 6900, 'defaut'],
                ['Coupe-boulon', 4100, 'upn'],
                ['Pince à tuyau', 13500, 'tube-rond'],
            ],
            'Coupe, sciage et frappe' => [
                ['Scie à métaux', 15000, 'defaut'],
                ['Scie à bois', 7600, 'defaut'],
                ['Scie égoïne', 5600, 'defaut'],
                ['Scie japonaise', 8100, 'defaut'],
                ['Scie PVC', 14000, 'defaut'],
                ['Lame de scie à métaux', 15000, 'defaut'],
                ['Cutter', 9200, 'defaut'],
                ['Lame cutter', 7000, 'defaut'],
                ['Ciseau à bois', 14500, 'defaut'],
                ['Ciseau à métal', 3400, 'defaut'],
                ['Burin plat', 9900, 'marteau'],
                ['Burin pointe', 12500, 'clou'],
                ['Pointeau', 14500, 'clou'],
            ],
            'Mesure' => [
                ['Mètre ruban', 39000, 'defaut'],
                ['Mètre pliant', 3100, 'defaut'],
                ['Règle métallique', 11000, 'defaut'],
                ['Équerre', 31500, 'defaut'],
                ['Équerre de menuisier', 12500, 'defaut'],
                ['Niveau à bulle', 17000, 'defaut'],
                ['Niveau laser', 32000, 'defaut'],
                ['Fil à plomb', 39500, 'fil'],
                ['Pied à coulisse', 41500, 'defaut'],
                ['Jauge d\'épaisseur', 15500, 'defaut'],
                ['Rapporteur', 12000, 'defaut'],
                ['Décamètre', 43000, 'defaut'],
            ],
            'Usinage et serrage' => [
                ['Lime plate', 26500, 'defaut'],
                ['Lime ronde', 26500, 'rond-lisse'],
                ['Lime carrée', 26500, 'defaut'],
                ['Lime demi-ronde', 21500, 'rond-lisse'],
                ['Râpe', 20000, 'defaut'],
                ['Étau d\'établi', 12500, 'defaut'],
                ['Serre-joint', 18500, 'defaut'],
                ['Pince de serrage', 16500, 'defaut'],
                ['Taraud', 24500, 'defaut'],
                ['Filière', 17000, 'fil'],
                ['Jeu de tarauds', 4100, 'defaut'],
                ['Jeu de filières', 29500, 'fil'],
                ['Extracteur', 18000, 'defaut'],
                ['Arrache-moyeu', 24500, 'defaut'],
            ],
        ],
    ],
    'Outillage électrique' => [
        'icone' => 'electrique',
        'sous' => [
            'Perçage et vissage' => [
                ['Perceuse', 33000, 'defaut'],
                ['Perceuse à percussion', 127000, 'defaut'],
                ['Perceuse-visseuse', 79000, 'vis'],
                ['Visseuse électrique', 127000, 'vis'],
                ['Visseuse à choc', 75000, 'vis'],
                ['Perforateur', 158000, 'defaut'],
                ['Marteau perforateur', 86000, 'marteau'],
                ['Burineur', 37000, 'marteau'],
            ],
            'Meulage et ponçage' => [
                ['Meuleuse d\'angle', 68000, 'disque'],
                ['Meuleuse droite', 45500, 'disque'],
                ['Polisseuse', 78000, 'defaut'],
                ['Ponceuse orbitale', 80000, 'defaut'],
                ['Ponceuse vibrante', 85000, 'defaut'],
                ['Ponceuse à bande', 103000, 'defaut'],
            ],
            'Découpe et menuiserie' => [
                ['Scie sauteuse', 96000, 'defaut'],
                ['Scie circulaire', 55000, 'defaut'],
                ['Scie sabre', 88000, 'defaut'],
                ['Scie à onglet', 98000, 'defaut'],
                ['Rabot électrique', 160000, 'defaut'],
                ['Défonceuse', 116000, 'defaut'],
                ['Découpeuse', 120000, 'upn'],
                ['Tronçonneuse', 82000, 'defaut'],
            ],
            'Autres machines' => [
                ['Décapeur thermique', 340000, 'defaut'],
                ['Agrafeuse électrique', 156000, 'clou'],
                ['Cloueur électrique', 377000, 'clou'],
                ['Compresseur', 315000, 'defaut'],
                ['Nettoyeur haute pression', 65000, 'defaut'],
                ['Groupe électrogène', 65000, 'upn'],
                ['Poste multifonction', 418000, 'defaut'],
            ],
            'Accessoires' => [
                ['Foret béton', 21000, 'defaut'],
                ['Foret métal', 17500, 'defaut'],
                ['Foret bois', 19500, 'defaut'],
                ['Foret étagé', 21000, 'defaut'],
                ['Foret SDS', 14500, 'defaut'],
                ['Embout de vissage', 4600, 'vis'],
                ['Porte-embout', 15500, 'defaut'],
                ['Disque à tronçonner', 5100, 'disque'],
                ['Disque à meuler', 20500, 'disque'],
                ['Disque diamant', 5000, 'disque'],
                ['Disque à lamelles', 21000, 'disque'],
                ['Brosse métallique', 21000, 'defaut'],
                ['Lame circulaire', 5300, 'defaut'],
                ['Lame scie sauteuse', 7800, 'defaut'],
                ['Lame scie sabre', 14500, 'defaut'],
                ['Papier abrasif', 20500, 'disque'],
            ],
        ],
    ],
    'Soudure et découpe' => [
        'icone' => 'soudure',
        'sous' => [
            'Postes' => [
                ['Poste à souder MMA', 258000, 'defaut'],
                ['Poste inverter', 99000, 'defaut'],
                ['Poste MIG', 217000, 'defaut'],
                ['Poste MAG', 215000, 'defaut'],
                ['Poste TIG', 219000, 'defaut'],
                ['Poste plasma', 375000, 'defaut'],
                ['Poste multiprocédé', 119000, 'defaut'],
            ],
            'Consommables' => [
                ['Électrode rutile', 9100, 'electrode'],
                ['Électrode basique', 20000, 'electrode'],
                ['Électrode inox', 10500, 'electrode'],
                ['Électrode fonte', 14000, 'electrode'],
                ['Électrode aluminium', 4500, 'electrode'],
                ['Fil MIG', 5900, 'electrode'],
                ['Fil MAG', 4100, 'fil'],
                ['Fil TIG', 7200, 'electrode'],
                ['Baguette TIG', 4200, 'electrode'],
                ['Fil d\'apport', 23000, 'fil'],
                ['Flux de soudure', 10500, 'defaut'],
                ['Décapant', 6700, 'defaut'],
            ],
            'Accessoires' => [
                ['Porte-électrode', 21500, 'electrode'],
                ['Pince de masse', 21500, 'marteau'],
                ['Torche MIG', 20000, 'defaut'],
                ['Torche TIG', 1500, 'defaut'],
                ['Buse MIG', 21000, 'defaut'],
                ['Buse TIG', 2300, 'defaut'],
                ['Diffuseur', 20000, 'defaut'],
                ['Tube contact', 7600, 'tube-rond'],
                ['Détendeur', 5900, 'defaut'],
                ['Manomètre', 4300, 'defaut'],
                ['Tuyau gaz', 1800, 'tube-rond'],
                ['Régulateur gaz', 12000, 'defaut'],
                ['Câble de soudage', 2800, 'fil'],
                ['Connecteur de câble', 21000, 'fil'],
            ],
            'Découpe' => [
                ['Disque tronçonnage métal', 18000, 'disque'],
                ['Disque inox', 4200, 'disque'],
                ['Disque aluminium', 3300, 'disque'],
                ['Disque diamant', 8000, 'disque'],
                ['Buse plasma', 14500, 'defaut'],
            ],
            'Protection' => [
                ['Masque de soudure', 38000, 'defaut'],
                ['Masque automatique', 17000, 'defaut'],
                ['Lunettes soudage', 23500, 'defaut'],
                ['Gants soudage', 16000, 'defaut'],
                ['Tablier cuir', 4600, 'defaut'],
                ['Manchettes', 18000, 'defaut'],
                ['Guêtres', 8700, 'defaut'],
                ['Chaussures sécurité', 35500, 'defaut'],
                ['Vêtement ignifugé', 18000, 'defaut'],
            ],
        ],
    ],
    'Peinture et colles' => [
        'icone' => 'peinture',
        'sous' => [
            'Peintures' => [
                ['Peinture antirouille', 24000, 'defaut'],
                ['Peinture métal', 9600, 'defaut'],
                ['Peinture glycéro', 16000, 'defaut'],
                ['Peinture acrylique', 7400, 'defaut'],
                ['Peinture industrielle', 23500, 'defaut'],
                ['Peinture époxy', 22000, 'defaut'],
                ['Apprêt', 31000, 'defaut'],
                ['Primaire anticorrosion', 8000, 'defaut'],
                ['Vernis', 6500, 'defaut'],
            ],
            'Produits chimiques' => [
                ['Diluant', 10000, 'defaut'],
                ['White-spirit', 10500, 'defaut'],
                ['Solvant', 11000, 'defaut'],
                ['Décapant', 10000, 'defaut'],
                ['Durcisseur', 8300, 'defaut'],
                ['Dégraissant', 9900, 'defaut'],
                ['Nettoyant frein', 8100, 'defaut'],
            ],
            'Colles et mastics' => [
                ['Mastic', 11500, 'defaut'],
                ['Mastic polyester', 6800, 'defaut'],
                ['Mastic silicone', 9700, 'defaut'],
                ['Silicone sanitaire', 13000, 'defaut'],
                ['Silicone neutre', 13000, 'defaut'],
                ['Colle contact', 7700, 'defaut'],
                ['Colle époxy', 2600, 'defaut'],
                ['Colle PVC', 2900, 'defaut'],
                ['Colle métal', 6100, 'defaut'],
                ['Colle cyanoacrylate', 4200, 'defaut'],
                ['Colle néoprène', 4900, 'defaut'],
                ['Pâte à joint', 4900, 'defaut'],
            ],
            'Application' => [
                ['Pinceau', 1400, 'defaut'],
                ['Rouleau', 4000, 'defaut'],
                ['Bac à peinture', 9300, 'defaut'],
                ['Spatule', 4400, 'truelle'],
                ['Couteau à enduire', 7100, 'defaut'],
                ['Pistolet à peinture', 9400, 'tole-plane'],
                ['Ruban de masquage', 8400, 'defaut'],
                ['Bâche de protection', 3000, 'defaut'],
                ['Éponge abrasive', 8800, 'defaut'],
            ],
        ],
    ],
    'Plomberie' => [
        'icone' => 'plomberie',
        'sous' => [
            'Tuyaux' => [
                ['Tube PVC', 13000, 'tube-rond'],
                ['Tube PVC pression', 15000, 'tube-rond'],
                ['Tube PPR', 16000, 'tube-rond'],
                ['Tube PER', 13000, 'tube-rond'],
                ['Tube cuivre', 4000, 'tube-rond'],
                ['Tube multicouche', 13000, 'tube-rond'],
                ['Tuyau flexible', 10000, 'tube-rond'],
            ],
            'Raccords' => [
                ['Coude PVC', 6300, 'defaut'],
                ['Coude PPR', 2800, 'defaut'],
                ['Coude cuivre', 7100, 'defaut'],
                ['Té PVC', 7000, 'defaut'],
                ['Té PPR', 2500, 'defaut'],
                ['Manchon', 2900, 'defaut'],
                ['Réduction', 2600, 'defaut'],
                ['Bouchon', 4300, 'defaut'],
                ['Adaptateur', 900, 'defaut'],
                ['Raccord fileté', 7100, 'fil'],
                ['Raccord rapide', 2400, 'defaut'],
                ['Raccord compression', 5400, 'defaut'],
            ],
            'Robinetterie' => [
                ['Robinet', 14500, 'defaut'],
                ['Robinet d\'arrêt', 33500, 'defaut'],
                ['Robinet mélangeur', 34500, 'defaut'],
                ['Mitigeur', 15000, 'defaut'],
                ['Vanne', 28500, 'defaut'],
                ['Vanne papillon', 37000, 'defaut'],
                ['Vanne à bille', 13500, 'defaut'],
                ['Clapet anti-retour', 16500, 'defaut'],
                ['Détendeur', 26000, 'defaut'],
            ],
            'Évacuation' => [
                ['Siphon', 900, 'defaut'],
                ['Bonde', 4100, 'defaut'],
                ['Flexible évacuation', 7900, 'tube-rond'],
                ['Grille d\'évacuation', 5800, 'defaut'],
                ['Regard', 4500, 'defaut'],
                ['Joint', 8000, 'defaut'],
                ['Joint torique', 5000, 'defaut'],
                ['Joint fibre', 6200, 'defaut'],
                ['Ruban téflon', 5400, 'defaut'],
                ['Colle PVC', 4600, 'defaut'],
                ['Filasse', 4200, 'fil'],
                ['Pâte à joint', 4200, 'defaut'],
            ],
        ],
    ],
    'Électricité' => [
        'icone' => 'electricite',
        'sous' => [
            'Câbles et conduits' => [
                ['Câble électrique', 30000, 'fil'],
                ['Fil électrique rigide', 10000, 'fil'],
                ['Fil électrique souple', 34500, 'fil'],
                ['Câble multipolaire', 9900, 'fil'],
                ['Gaine électrique', 21500, 'tube-rond'],
                ['Gaine annelée', 21000, 'tube-rond'],
                ['Tube électrique', 40000, 'tube-rond'],
            ],
            'Appareillage' => [
                ['Prise', 19000, 'defaut'],
                ['Interrupteur', 38500, 'defaut'],
                ['Va-et-vient', 1300, 'defaut'],
                ['Prise étanche', 2600, 'defaut'],
                ['Disjoncteur', 23500, 'defaut'],
                ['Fusible', 27500, 'defaut'],
                ['Porte-fusible', 19000, 'defaut'],
                ['Tableau électrique', 8200, 'defaut'],
                ['Coffret électrique', 11000, 'defaut'],
                ['Contacteur', 18500, 'defaut'],
                ['Relais', 1400, 'defaut'],
                ['Bornier', 30500, 'defaut'],
                ['Domino', 3000, 'defaut'],
                ['Connecteur Wago', 27500, 'defaut'],
                ['Cosse électrique', 31000, 'defaut'],
                ['Serre-câble', 31500, 'fil'],
                ['Gaine thermorétractable', 31000, 'tube-rond'],
                ['Ruban isolant', 21500, 'defaut'],
            ],
            'Éclairage' => [
                ['Ampoule LED', 19000, 'defaut'],
                ['Ampoule halogène', 4900, 'defaut'],
                ['Douille', 7400, 'defaut'],
                ['Plafonnier', 11000, 'defaut'],
                ['Projecteur LED', 26500, 'defaut'],
                ['Lampe LED', 25000, 'defaut'],
                ['Réglette LED', 17000, 'defaut'],
                ['Ruban LED', 25000, 'defaut'],
                ['Détecteur de mouvement', 3300, 'defaut'],
            ],
        ],
    ],
    'Pièces auto' => [
        'icone' => 'piece',
        'sous' => [
            'Moteur' => [
                ['Filtre à air', 122000, 'fil'],
                ['Filtre à huile', 49000, 'fil'],
                ['Filtre à carburant', 133000, 'fil'],
                ['Filtre habitacle', 146000, 'fil'],
                ['Bougie d\'allumage', 13500, 'defaut'],
                ['Bougie de préchauffage', 88000, 'defaut'],
                ['Injecteur', 185000, 'defaut'],
                ['Pompe à carburant', 62000, 'defaut'],
                ['Pompe à huile', 174000, 'defaut'],
                ['Pompe à eau', 74000, 'defaut'],
                ['Courroie distribution', 10000, 'courroie'],
                ['Courroie accessoire', 7300, 'courroie'],
                ['Tendeur', 116000, 'defaut'],
                ['Galet', 63000, 'poulie'],
                ['Poulie', 86000, 'poulie'],
                ['Joint culasse', 170000, 'defaut'],
                ['Joint moteur', 127000, 'defaut'],
                ['Culasse', 115000, 'defaut'],
                ['Soupape', 114000, 'defaut'],
                ['Piston', 90000, 'defaut'],
                ['Segment', 116000, 'defaut'],
                ['Bielle', 84000, 'defaut'],
                ['Vilebrequin', 88000, 'defaut'],
                ['Arbre à cames', 169000, 'defaut'],
                ['Carter', 88000, 'defaut'],
                ['Thermostat', 47000, 'defaut'],
                ['Radiateur', 184000, 'defaut'],
                ['Ventilateur', 90000, 'defaut'],
                ['Durite', 88000, 'tube-rond'],
                ['Intercooler', 87000, 'defaut'],
                ['Turbo', 64000, 'defaut'],
                ['Silencieux', 44500, 'defaut'],
                ['Catalyseur', 48500, 'defaut'],
                ['FAP', 21000, 'defaut'],
            ],
            'Embrayage et transmission' => [
                ['Kit embrayage', 65000, 'defaut'],
                ['Disque embrayage', 86000, 'disque'],
                ['Mécanisme embrayage', 148000, 'defaut'],
                ['Butée embrayage', 44000, 'defaut'],
                ['Volant moteur', 76000, 'defaut'],
                ['Cardan', 97000, 'defaut'],
                ['Soufflet cardan', 163000, 'defaut'],
                ['Arbre transmission', 106000, 'defaut'],
                ['Différentiel', 54000, 'defaut'],
                ['Boîte vitesses', 148000, 'defaut'],
                ['Support moteur', 135000, 'defaut'],
                ['Support boîte', 121000, 'defaut'],
            ],
            'Freinage' => [
                ['Plaquettes frein', 47500, 'defaut'],
                ['Disques frein', 32500, 'disque'],
                ['Tambours', 75000, 'defaut'],
                ['Mâchoires', 37000, 'defaut'],
                ['Étrier', 16000, 'defaut'],
                ['Kit frein', 15500, 'defaut'],
                ['Maître-cylindre', 8600, 'cadenas'],
                ['Cylindre roue', 32000, 'cadenas'],
                ['Flexible frein', 78000, 'tube-rond'],
                ['Capteur ABS', 52000, 'defaut'],
                ['Liquide frein', 27000, 'defaut'],
            ],
            'Suspension' => [
                ['Amortisseur', 34500, 'defaut'],
                ['Ressort', 45000, 'defaut'],
                ['Coupelle', 70000, 'upn'],
                ['Silentbloc', 61000, 'defaut'],
                ['Triangle', 68000, 'defaut'],
                ['Rotule', 13000, 'defaut'],
                ['Biellette', 24000, 'defaut'],
                ['Barre stabilisatrice', 72000, 'rond-lisse'],
                ['Roulement', 26500, 'roulement'],
                ['Moyeu', 73000, 'defaut'],
                ['Bras suspension', 71000, 'defaut'],
            ],
            'Direction' => [
                ['Rotule direction', 25000, 'defaut'],
                ['Biellette direction', 83000, 'defaut'],
                ['Crémaillère', 37500, 'defaut'],
                ['Pompe direction', 36000, 'defaut'],
                ['Colonne direction', 88000, 'defaut'],
                ['Volant', 26000, 'defaut'],
            ],
            'Électricité automobile' => [
                ['Batterie', 56000, 'defaut'],
                ['Alternateur', 92000, 'defaut'],
                ['Démarreur', 16500, 'defaut'],
                ['Relais', 87000, 'defaut'],
                ['Fusible', 23000, 'defaut'],
                ['Ampoule', 26000, 'defaut'],
                ['Phare', 62000, 'defaut'],
                ['Feu arrière', 27000, 'defaut'],
                ['Clignotant', 45500, 'defaut'],
                ['Klaxon', 89000, 'defaut'],
                ['Bobine allumage', 90000, 'defaut'],
                ['Capteur', 28500, 'defaut'],
                ['Sonde', 62000, 'defaut'],
                ['Régulateur', 57000, 'defaut'],
                ['Moteur essuie-glace', 65000, 'defaut'],
                ['Essuie-glace', 17000, 'defaut'],
            ],
            'Carrosserie' => [
                ['Rétroviseur', 65000, 'vis'],
                ['Pare-chocs', 99000, 'defaut'],
                ['Aile', 45000, 'defaut'],
                ['Capot', 68000, 'defaut'],
                ['Porte', 68000, 'defaut'],
                ['Poignée', 32500, 'defaut'],
                ['Serrure', 9200, 'cadenas'],
                ['Charnière', 105000, 'charniere'],
                ['Grille', 89000, 'defaut'],
                ['Calandre', 34000, 'defaut'],
                ['Pare-brise', 100000, 'defaut'],
                ['Vitre', 67000, 'defaut'],
                ['Joint vitre', 35000, 'defaut'],
                ['Vérin coffre', 82000, 'defaut'],
            ],
        ],
    ],
    'Pièces machines' => [
        'icone' => 'piece',
        'sous' => [
            'Mécanique' => [
                ['Charbon moteur', 33500, 'defaut'],
                ['Induit', 4900, 'defaut'],
                ['Stator', 5900, 'defaut'],
                ['Rotor', 23500, 'defaut'],
                ['Roulement', 18000, 'roulement'],
                ['Palier', 43500, 'roulement'],
                ['Courroie', 22500, 'courroie'],
                ['Poulie', 44000, 'poulie'],
                ['Engrenage', 8800, 'defaut'],
                ['Pignon', 3900, 'defaut'],
                ['Chaîne', 19500, 'chaine'],
                ['Joint', 22500, 'defaut'],
                ['Ressort', 36500, 'defaut'],
                ['Carter', 4000, 'defaut'],
            ],
            'Électrique' => [
                ['Interrupteur', 30500, 'defaut'],
                ['Condensateur', 21000, 'defaut'],
                ['Câble', 8200, 'fil'],
                ['Prise', 32000, 'defaut'],
                ['Ventilateur', 3200, 'defaut'],
                ['Gâchette', 5100, 'defaut'],
                ['Batterie', 25000, 'defaut'],
                ['Chargeur', 28000, 'defaut'],
                ['Brosse carbone', 9400, 'defaut'],
            ],
            'Pièces de travail' => [
                ['Mandrin', 13000, 'defaut'],
                ['Porte-outil', 7500, 'defaut'],
                ['Lame', 15000, 'defaut'],
                ['Disque', 12000, 'disque'],
                ['Brosse métallique', 12500, 'defaut'],
                ['Plateau ponçage', 3600, 'defaut'],
                ['Foret', 13000, 'defaut'],
            ],
        ],
    ],
    'Agriculture' => [
        'icone' => 'agriculture',
        'sous' => [
            'Outils' => [
                ['Pelle', 3600, 'pelle'],
                ['Pioche', 26000, 'pelle'],
                ['Houe', 14000, 'pelle'],
                ['Hache', 30000, 'defaut'],
                ['Machette', 30500, 'defaut'],
                ['Râteau', 9500, 'pelle'],
                ['Fourche', 26000, 'defaut'],
                ['Bêche', 11500, 'pelle'],
                ['Serfouette', 25500, 'defaut'],
                ['Faucille', 28000, 'defaut'],
                ['Sécateur', 14500, 'defaut'],
                ['Cisaille', 28000, 'defaut'],
                ['Brouette', 5900, 'brouette'],
                ['Arrosoir', 7800, 'defaut'],
            ],
            'Irrigation et pompage' => [
                ['Tuyau arrosage', 121000, 'tube-rond'],
                ['Pulvérisateur', 117000, 'defaut'],
                ['Pompe', 63000, 'defaut'],
                ['Motopompe', 44500, 'defaut'],
                ['Tuyau hydraulique', 42500, 'tube-rond'],
                ['Raccord irrigation', 99000, 'defaut'],
                ['Robinet irrigation', 102000, 'defaut'],
                ['Filtre irrigation', 33500, 'fil'],
            ],
            'Accessoires' => [
                ['Chaîne', 18500, 'chaine'],
                ['Corde', 17500, 'fil'],
                ['Câble', 4800, 'fil'],
                ['Jerrican', 17500, 'defaut'],
                ['Bidon', 18500, 'defaut'],
                ['Seau', 19500, 'defaut'],
            ],
        ],
    ],
    'Portes et portails' => [
        'icone' => 'portail',
        'sous' => [
            'Quincaillerie' => [
                ['Serrure portail', 33000, 'cadenas'],
                ['Cylindre', 21500, 'cadenas'],
                ['Cadenas', 49500, 'cadenas'],
                ['Poignée', 17000, 'defaut'],
                ['Charnière', 28000, 'charniere'],
                ['Paumelle', 20500, 'charniere'],
                ['Gond', 41500, 'charniere'],
                ['Pivot', 3700, 'defaut'],
                ['Verrou', 28500, 'cadenas'],
                ['Targette', 23000, 'cadenas'],
                ['Butée', 19000, 'defaut'],
                ['Ferme-porte', 8900, 'defaut'],
                ['Rail', 41500, 'defaut'],
                ['Roulette', 25000, 'defaut'],
                ['Galet', 62000, 'poulie'],
                ['Crémone', 4500, 'defaut'],
                ['Espagnolette', 6700, 'defaut'],
                ['Compas', 25000, 'defaut'],
                ['Loquet', 27500, 'defaut'],
            ],
            'Portail' => [
                ['Arrêt portail', 98000, 'defaut'],
                ['Poignée portail', 214000, 'defaut'],
                ['Serrure portail renforcée', 234000, 'cadenas'],
                ['Gâche portail', 83000, 'defaut'],
                ['Gond réglable', 99000, 'charniere'],
                ['Motorisation portail', 263000, 'defaut'],
                ['Télécommande portail', 277000, 'defaut'],
                ['Crémaillère portail', 233000, 'defaut'],
            ],
            'Fenêtre' => [
                ['Poignée fenêtre', 12000, 'defaut'],
                ['Crémone fenêtre', 15500, 'defaut'],
                ['Gâche fenêtre', 12500, 'defaut'],
                ['Joint fenêtre', 8400, 'defaut'],
                ['Roulette fenêtre', 7600, 'defaut'],
                ['Compas fenêtre', 2600, 'defaut'],
            ],
        ],
    ],
    'Protection (EPI)' => [
        'icone' => 'epi',
        'sous' => [
            'Protection individuelle' => [
                ['Casque chantier', 23500, 'defaut'],
                ['Lunettes protection', 25000, 'defaut'],
                ['Gants protection', 30000, 'defaut'],
                ['Gants anti-coupure', 3400, 'defaut'],
                ['Gants manutention', 28500, 'defaut'],
                ['Gants soudage', 18000, 'defaut'],
                ['Masque poussière', 23000, 'defaut'],
                ['Masque respiratoire', 24000, 'defaut'],
                ['Protection auditive', 9100, 'defaut'],
                ['Bouchons oreilles', 12000, 'defaut'],
                ['Chaussures sécurité', 30500, 'defaut'],
                ['Bottes sécurité', 5600, 'defaut'],
                ['Gilet réfléchissant', 3200, 'defaut'],
                ['Combinaison travail', 3100, 'defaut'],
                ['Tablier', 2500, 'defaut'],
                ['Genouillères', 33000, 'defaut'],
                ['Harnais', 3800, 'defaut'],
                ['Visière', 27500, 'vis'],
                ['Masque soudage', 34000, 'defaut'],
            ],
        ],
    ],
    'Consommables' => [
        'icone' => 'defaut',
        'sous' => [
            'Abrasifs' => [
                ['Papier abrasif', 11000, 'disque'],
                ['Toile émeri', 7100, 'disque'],
                ['Disque abrasif', 1900, 'disque'],
                ['Disque lamelles', 1500, 'disque'],
                ['Meule', 5200, 'disque'],
                ['Pierre à aiguiser', 5100, 'defaut'],
                ['Brosse métallique', 9100, 'defaut'],
            ],
            'Fixation et emballage' => [
                ['Ruban adhésif', 3300, 'defaut'],
                ['Ruban double face', 7900, 'defaut'],
                ['Ficelle', 900, 'fil'],
                ['Corde', 4500, 'fil'],
                ['Sangle', 5000, 'fil'],
                ['Film étirable', 3600, 'fil'],
                ['Collier plastique', 1100, 'defaut'],
            ],
            'Nettoyage et entretien' => [
                ['Graisse', 12000, 'defaut'],
                ['Huile moteur', 1600, 'defaut'],
                ['Huile mécanique', 7200, 'defaut'],
                ['Lubrifiant', 5700, 'defaut'],
                ['Dégrippant', 6100, 'defaut'],
                ['Nettoyant contact', 10500, 'defaut'],
                ['Nettoyant carburateur', 3300, 'defaut'],
                ['Chiffon atelier', 13000, 'defaut'],
                ['Brosse nettoyage', 12000, 'defaut'],
            ],
        ],
    ],
];
